### ISSUE TITLE
High Sierra

### ISSUE THREAD

**Issue by mhulse** [shaunplee/homebrew-rhyme#1]
Doesn't seem to work out of box on High Sierra 10.13.6 (17G65)

I tapped, then installed. Next, ran:

```bash
$ which rhyme
(nothing)
```

Also reloaded profile and restarted my terminal.

Not sure if this repo is maintained anymore, just thought I would leave a message.

Thanks!

**Comment by shaunplee** [comment]
Wow! Another user!

I think I've fixed the problem. Will you please `brew update` and `brew install rhyme` again?

**Comment by mhulse** [comment]
Awesome! That fixed it! Thanks a bunch @shaunplee!!!! I really appreciate it. 👍
